- alias: Automatic Bar Lighting
  trigger:
  - platform: state
    entity_id: light.bar_bulb_1
    to: 'on'
  - platform: time
    minutes: '/1'
    seconds: 00
  action:
  - service: switch.bar_automatic_lighting_update

- alias: Office Lights On
  trigger:
  - platform: time
    at: '7:00:00'
  condition:
  - condition: state
    entity_id: 'binary_sensor.workday_sensor_be'
    state: 'on'
  action:
    service: light.turn_on
    data:
      entity_id:
      - light.sonoff1645
      - light.sonoff1905
      - light.sonoff1911
      - switch.systvscreen
      - switch.kafiscreen

- alias: Office Lights Off
  trigger:
  - platform: time
    at: '20:00:00'
  condition:
    condition: state
    entity_id: 'binary_sensor.workday_sensor_be'
    state: 'on'
  action:
    service: light.turn_off
    data:
      entity_id:
      - light.sonoff1645
      - light.sonoff1905
      - light.sonoff1911
      - switch.systvscreen
      - switch.kafiscreen
