homeassistant:
  name: Puzzle Assistant
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: !secret ha_elevation
  unit_system: !secret ha_unit_system
  time_zone: !secret ha_time_zone
  customize: !include customize.yaml

frontend:
  themes:
    puzzle:
      primary-color: "#1E5A96"
      primary-background-color: "#FFFFFF"
      secondary-background-color: "#FFFFFF"

http:
  server_port: !secret http_server_port
  base_url: !secret http_base_url

updater:
  reporting: false
  include_used_components: false

history:

logbook:
  exclude:
    entities:
    - automation.automatic_bar_lighting

sun:

notify: !include notifiers.yaml

mqtt:
  broker: !secret mqtt_host

light: !include lights.yaml

tradfri:
  host: !secret tradfri_host

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

binary_sensor: !include binary_sensors.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml

input_boolean: !include input_booleans.yaml
group: !include groups.yaml
scene: !include scenes.yaml
automation: !include automations.yaml

octoprint:
  host: !secret octoprint_host 
  api_key: !secret octoprint_api_key
  bed: true
  sensors:
    monitored_conditions:
      - 'Current State'
      - 'Temperatures'
      - 'Job Percentage'
      - 'Time Elapsed'
      - 'Time Remaining'
  binary_sensors:
    monitored_conditions:
      - 'Printing'
      - 'Printing Error'

