- platform: demo
  name: sonoff1905
- platform: demo
  name: sonoff7461
- platform: demo
  name: sonoff4126
- platform: demo
  name: sonoff1911
- platform: demo
  name: sonoff1645
- platform: demo
  name: bar_bulb_1
- platform: demo
  name: bar_bulb_2
- platform: demo
  name: bar_bulb_3
- platform: demo
  name: bar_bulb_4
- platform: demo
  name: bar_bulb_5
