title: Puzzle Assistant
views:
  - title: Puzzle Assistant
    icon: mdi:puzzle
  - title: 3D Printer
    icon: mdi:printer-3d
    cards:
      - type: glance
        title: Printer State
        entities:
          - binary_sensor.octoprint_printing
          - binary_sensor.octoprint_printing_error

      - type: entities
        title: Job State
        entities:
          - sensor.octoprint_current_state
          - sensor.octoprint_job_percentage
          - sensor.octoprint_actual_bed_temp
          - sensor.octoprint_target_bed_temp
          - sensor.octoprint_time_elapsed
          - sensor.octoprint_time_remaining
  - title: Settings
    icon: mdi:settings
