title: Puzzle Assistant
views:
- title: Puzzle
  icon: mdi:puzzle
  cards:
  - type: glance
    title: Bar
    entities:
    - entity: automation.automatic_bar_lighting
      name: Automatic Lighting
      icon: mdi:weather-sunset
    - entity: switch.kafiscreen
      name: 'Kafi Screen'
      icon: mdi:television
    - entity: switch.altekaffemaschine
      name: 'Alte Kaffeemaschine'
      icon: mdi:coffee
    - entity: switch.wasserspender
      name: 'Wasserspender'
      icon: mdi:water-pump
    - entity: switch.bierkuehlschrank
      name: 'Bierkühlschrank'
      icon: mdi:fridge
    - entity: switch.kaffeemuehle
      name: 'Kaffeemühle'
      icon: mdi:coffee
  - type: glance
    title: Backoffice
    entities:
    - entity: light.sonoff1905
      name: Floor Lamp 1
      icon: mdi:floor-lamp
    - entity: input_boolean.sonoff1905_timebased_lighting
      name: Time-Based Lighting
      icon: mdi:clock-outline
    - entity: switch.gangscreen
      name: Gang Screen
      icon: mdi:television
  - type: glance
    title: /dev/tre
    entities:
    - entity: light.sonoff1645
      name: Floor Lamp 1
      icon: mdi:floor-lamp
    - entity: input_boolean.sonoff1645_timebased_lighting
      name: Time-Based Lighting
      icon: mdi:clock-outline
    - entity: switch.swoascreen
      name: SWOA Screen
      icon: mdi:television
  - type: glance
    title: /dev/ruby
    entities:
    - entity: switch.rubyscreen
      name: Ruby Screen
      icon: mdi:television
  - type: glance
    title: /sys & /mid
    entities:
    - entity: light.sonoff1911
      name: Floor Lamp 1
      icon: mdi:floor-lamp
    - entity: input_boolean.sonoff1911_timebased_lighting
      name: Time-Based Lighting
      icon: mdi:clock-outline
    - entity:  switch.systvscreen
      name: TV Screen
      icon: mdi:television
    - entity:  switch.apstandardt
      name: AP Srandard T
      icon: mdi:account-question
    - entity: switch.drucker
      name: 'Drucker'
      icon: mdi:printer
    - entity: switch.apneuc
      name: 'AP Neu C'
      icon: mdi:account-question
    - entity: switch.apaltj
      name: 'AP Alt J'
      icon: mdi:account-question
  - type: glance
    title: TUX
    entities:
    - entity: light.sonoff7461
      name: Floor Lamp 1
      icon: mdi:floor-lamp
    - entity: light.sonoff4126
      name: Floor Lamp 2
      icon: mdi:floor-lamp
    - entity: switch.sonoff1688
      name: Projector
      icon: mdi:projector
  - type: glance
    title: Pouse
    entities:
    - entity: switch.mikrowelleunten
      name: 'Mikrowelle unten'
      icon: mdi:microwave
    - entity: switch.mikrowelleoben
      name: 'Mikrowelle oben'
      icon: mdi:microwave
- title: Settings
  icon: mdi:settings
  cards:
  - type: light
    name: Bar Bulb 1
    entity: light.bar_bulb_1
  - type: light
    name: Bar Bulb 2
    entity: light.bar_bulb_2
  - type: light
    name: Bar Bulb 3
    entity: light.bar_bulb_3
  - type: light
    name: Bar Bulb 4
    entity: light.bar_bulb_4
  - type: light
    name: Bar Bulb 5
    entity: light.bar_bulb_5
- title: Energy
  icon: mdi:power-plug
  cards:
  - type: sensor
    name: Power Statistics
    unit: W
    entity: sensor.power_total
    graph: line
  - type: sensor
    entity: sensor.energy_total
    name: Energy Statistics
    unit: kWh
    graph: line
